Reparando bugs encontrados en las pruebas
JobCore/api pull request #39
Opened 2019-04-16 15:37 UTC by josegomezr

Con estos cambios logramos 99% de éxito en las pruebas. Hay 1 sola fallando referente a las validaciones de perfil.

Ya se han reparado todos los bugs encontrados (las marcas @todo) y mejorado el coverage, está más cerca del 100% en algunos archivos. Aunque aún falta refractor para lograr el 100%.

2019-04-16 21:11 UTC, alacret requested changes

2019-04-16 21:11 UTC, alacret commented on api/actions/auth_actions.py
> +            invite = ShiftInvite(
reemplazar con bulk create

2019-04-16 21:11 UTC, alacret commented on api/serializers/auth_serializer.py
> +            user_obj = User.objects.filter(lookup)[:1].get()
Por que de esta manera y no con un .first? o un `get` directo?

2019-04-16 21:11 UTC, alacret commented on api/serializers/auth_serializer.py
> +            FCMDevice.objects.filter(registration_id=device_id).delete()
Haz un update o usa una transaccion

2019-04-16 21:11 UTC, alacret commented on api/serializers/auth_serializer.py
> +
no hagas estos try multilineas, el try debe ser para una sentencia nada mas y recuperar

2019-04-16 21:11 UTC, alacret commented on api/serializers/auth_serializer.py
> +
considera abstraer la logica de la creacion de un empledao y un employer en 2 funciones distintas

2019-04-16 21:11 UTC, alacret commented on api/serializers/rating_serializer.py
> +            try:
confirma con @alesanchezr que esto es asi

2019-04-16 21:14 UTC, josegomezr commented on api/serializers/auth_serializer.py
> +            user_obj = User.objects.filter(lookup)[:1].get()
Ah porque `[:1]` manda a escribir un `LIMIT 1` en la consulta generada. Para que `.get` no lanze un `MultipleObjectReturned` y siempre sea `DoesNotExist`

2019-04-16 21:15 UTC, josegomezr commented on api/serializers/auth_serializer.py
> +            FCMDevice.objects.filter(registration_id=device_id).delete()
Npi, esto es copypasteado de lo que estaba, exactamente que quieres decir con una TX? que el FCMDevice se "swap"-ee ? intercambio uno por otro pues?

2019-04-16 21:21 UTC, alacret commented on api/serializers/auth_serializer.py
> +            user_obj = User.objects.filter(lookup)[:1].get()
reemplazalo por un first mejor, o por un get y revisas ambas excepciones

2019-04-16 21:22 UTC, alacret commented on api/serializers/auth_serializer.py
> +            FCMDevice.objects.filter(registration_id=device_id).delete()
si, exacto, con el UPDATE garantizas que se mantenga consistente en cualquier fallo. Lo mismo lo haces con la transaccion. Pero creo que aqui el UPDATE sirve

2019-04-17 13:25 UTC, josegomezr commented on api/actions/auth_actions.py
> +            invite = ShiftInvite(
esto es legacy code...

2019-04-17 13:26 UTC, josegomezr commented on api/serializers/auth_serializer.py
> +            user_obj = User.objects.filter(lookup)[:1].get()
again, legacy code...

2019-04-17 13:26 UTC, josegomezr commented on api/serializers/auth_serializer.py
> +
again, legacy code...

2019-04-17 13:53 UTC, alacret commented on api/actions/auth_actions.py
> +            invite = ShiftInvite(
Lo entiendo, reparemoslo

2019-04-17 13:53 UTC, alacret commented on api/serializers/auth_serializer.py
> +            user_obj = User.objects.filter(lookup)[:1].get()
Lo entiendo, reparemoslo

2019-04-17 13:53 UTC, alacret commented on api/serializers/auth_serializer.py
> +
a este marcale con un todo, y luego lo hacemos

2019-04-18 02:44 UTC, alacret approved these changes

2019-04-18 02:44 UTC, merged